export enum CHECK_EVENT {
    IS_USERNAME_EXIST = 'IS_USERNAME_EXIST',
    GET_IP_ADDRESS = 'GET_IP_ADDRESS',
    USER_ADD = 'USER_ADD',
    FORCE_LOGOUT = 'FORCE_LOGOUT',

    IS_USERNAME_EXIST_MULTIPLE = 'IS_USERNAME_EXIST_MULTIPLE',
}